---
applications:
- name: hazardbot
  memory: 1G
  disk_quota: 500M
  instances: 1
  path: ../build/libs/hazardbot-0.0.1-SNAPSHOT.jar
  host: hazardbot-sb
  domain: clgxlabs.net
  buildpack: java_buildpack_offline-3_15
  services:
    - hazardbot-mysql
  env:
    SPRING_PROFILES_ACTIVE: sb
